spring:
  profiles: default
  data:
    mongodb:
      host: localhost
      username: user
      password: password
      database: koala
      port: 25000
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
    
---

spring:
  profiles: docker
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: password
      database: koala
      port: 27017
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
