spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
    
server:
  servlet:
    context-path: /uaa
  port: 5000
  
spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: koala
      port: 27017

---

spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
